/**
 * High-frequency sentence patterns — reusable Greek communication structures.
 * Consumed by lessons, hints, and guided paths.
 */
export const SENTENCE_PATTERNS = [
  {
    id: 'thelo-na',
    pattern: 'θέλω να…',
    english: 'I want to…',
    example: 'Θέλω να πάω σπίτι.',
    exampleEnglish: 'I want to go home.',
    insight: 'After θέλω, Greek uses να + verb — your intent points toward an action.',
    difficulty: 'beginner',
    tags: ['modal', 'intent'],
  },
  {
    id: 'mporo-na',
    pattern: 'μπορώ να…',
    english: 'I can / am able to…',
    example: 'Μπορώ να σε βοηθήσω;',
    exampleEnglish: 'Can I help you?',
    insight: 'Ability questions flip word order naturally: Μπορείς να…;',
    difficulty: 'beginner',
    tags: ['modal', 'ability'],
  },
  {
    id: 'prepei-na',
    pattern: 'πρέπει να…',
    english: 'I must / should / have to…',
    example: 'Πρέπει να διαβάσω.',
    exampleEnglish: 'I must study.',
    insight: 'πρέπει stays the same for all persons — only the verb after να changes.',
    difficulty: 'beginner',
    tags: ['modal', 'obligation'],
  },
  {
    id: 'mou-aresei',
    pattern: 'μου αρέσει…',
    english: 'I like… (lit. it pleases me)',
    example: 'Μου αρέσει ο καφές.',
    exampleEnglish: 'I like coffee.',
    insight: 'Greek expresses liking as something pleasing to you — μου comes first.',
    difficulty: 'beginner',
    tags: ['preference'],
  },
  {
    id: 'den-xero',
    pattern: 'δεν ξέρω…',
    english: "I don't know…",
    example: 'Δεν ξέρω τι να πω.',
    exampleEnglish: "I don't know what to say.",
    insight: 'Honest uncertainty — Greeks use this constantly in conversation.',
    difficulty: 'beginner',
    tags: ['uncertainty'],
  },
  {
    id: 'nomizo-oti',
    pattern: 'νομίζω ότι…',
    english: 'I think that…',
    example: 'Νομίζω ότι θα βρέξει.',
    exampleEnglish: 'I think it will rain.',
    insight: 'Soft opinions start with νομίζω — less blunt than a bare statement.',
    difficulty: 'beginner',
    tags: ['opinion'],
  },
  {
    id: 'mou-fainetai',
    pattern: 'μου φαίνεται…',
    english: 'it seems to me…',
    example: 'Μου φαίνεται καλή ιδέα.',
    exampleEnglish: 'It seems like a good idea to me.',
    insight: 'Even softer than νομίζω — you are sharing a impression, not a verdict.',
    difficulty: 'intermediate',
    tags: ['opinion'],
  },
  {
    id: 'tha-ithela',
    pattern: 'θα ήθελα…',
    english: 'I would like…',
    example: 'Θα ήθελα ένα νερό, παρακαλώ.',
    exampleEnglish: 'I would like a water, please.',
    insight: 'Polite requests in cafés and shops — warmer than a bare θέλω.',
    difficulty: 'beginner',
    tags: ['polite', 'requests'],
  },
  {
    id: 'den-peirazei',
    pattern: 'δεν πειράζει',
    english: "it doesn't matter / no problem",
    example: '— Συγγνώμη για την καθυστέρηση. — Δεν πειράζει.',
    exampleEnglish: '— Sorry for the delay. — No problem.',
    insight: 'Social glue — accepts apologies and resets the mood.',
    difficulty: 'beginner',
    tags: ['polite', 'glue'],
  },
  {
    id: 'pame',
    pattern: 'πάμε',
    english: "let's go",
    example: 'Πάμε για καφέ;',
    exampleEnglish: "Shall we go for coffee?",
    insight: 'Invitation + movement — one of the most natural spoken patterns.',
    difficulty: 'beginner',
    tags: ['invitation'],
  },
  {
    id: 'ti-kaneis',
    pattern: 'τι κάνεις;',
    english: 'how are you? (lit. what are you doing?)',
    example: '— Γεια! Τι κάνεις; — Καλά, εσύ;',
    exampleEnglish: '— Hi! How are you? — Good, you?',
    insight: 'Not always literal — this is the default casual greeting check-in.',
    difficulty: 'beginner',
    tags: ['greeting'],
  },
  {
    id: 'pou-pas',
    pattern: 'πού πας;',
    english: 'where are you going?',
    example: '— Πού πας; — Πάω στο σπίτι.',
    exampleEnglish: '— Where are you going? — I am going home.',
    insight: 'Present movement in Greek feels immediate — perfect for micro-dialogues.',
    difficulty: 'beginner',
    tags: ['movement', 'question'],
  },
]

export function getSentencePatternById(id) {
  return SENTENCE_PATTERNS.find((p) => p.id === id) ?? null
}
