const CATEGORY_EMOJI = {
  greetings: '👋',
  food: '🍽️',
  travel: '✈️',
  school: '📚',
  family: '👨‍👩‍👧',
  home: '🏠',
  body: '🧍',
  numbers: '🔢',
  colors: '🎨',
  time: '⏰',
  weather: '🌤️',
  shopping: '🛒',
  emotions: '💭',
  animals: '🐾',
  work: '💼',
  nature: '🌿',
  city: '🏙️',
  verbs: '💬',
  adjectives: '✨',
  technology: '💻',
  sports: '⚽',
  culture: '🇬🇷',
}

/** Common phrases → one clear visual (checked before single keywords). */
const PHRASE_EMOJI = {
  'good morning': '🌅',
  'good afternoon': '🌤️',
  'good evening': '🌆',
  'good night': '🌙',
  'thank you': '🙏',
  'how are you': '💬',
  'nice to meet': '🤝',
  'good luck': '🍀',
  'nice weekend': '📅',
  'enjoy your meal': '🍽️',
  'how much': '💶',
  'where is': '📍',
  'ice cream': '🍦',
  'olive oil': '🫒',
  'traffic light': '🚦',
  'post office': '📮',
  'fire department': '🚒',
  'living room': '🛋️',
  'washing machine': '🧺',
  'mobile phone': '📱',
  'capital city': '🏛️',
  'cash register': '🧾',
  'i am': '💬',
  'i have': '✋',
  'i go': '🚶',
  'i come': '👋',
  'i see': '👁️',
  'i hear': '👂',
  'i know': '💡',
  'i want': '🙏',
  'i can': '💪',
  'i eat': '🍽️',
  'i drink': '🥤',
  'i sleep': '😴',
  'i work': '💼',
  'i speak': '🗣️',
  'i think': '💭',
  'i love': '❤️',
  'i buy': '🛒',
  'i sell': '🏷️',
  'i help': '🤝',
  'i wait': '⏳',
  'i smile': '😊',
  'i cry': '😢',
  'i read': '📖',
  'i write': '✍️',
  'i learn': '📚',
  'i ask': '❓',
  'i answer': '💬',
  'i fly': '🕊️',
}

/** Headword → emoji (concrete, learner-friendly visuals). */
const KEYWORD_EMOJI = {
  hello: '👋',
  morning: '🌅',
  afternoon: '🌤️',
  evening: '🌆',
  night: '🌙',
  thank: '🙏',
  please: '🤲',
  sorry: '😔',
  yes: '✅',
  goodbye: '👋',
  welcome: '🤗',
  luck: '🍀',
  weekend: '📅',
  meal: '🍽️',
  fine: '👍',
  pleasure: '😊',
  water: '💧',
  bread: '🍞',
  milk: '🥛',
  cheese: '🧀',
  coffee: '☕',
  tea: '🍵',
  food: '🍽️',
  meat: '🥩',
  fish: '🐟',
  rice: '🍚',
  salad: '🥗',
  fruit: '🍎',
  apple: '🍎',
  orange: '🍊',
  egg: '🥚',
  sugar: '🧂',
  salt: '🧂',
  plate: '🍽️',
  glass: '🥛',
  fork: '🍴',
  knife: '🔪',
  breakfast: '🥐',
  lunch: '🥪',
  dinner: '🍝',
  hungry: '😋',
  thirsty: '🥤',
  vegetable: '🥬',
  chicken: '🍗',
  potato: '🥔',
  tomato: '🍅',
  olive: '🫒',
  honey: '🍯',
  pita: '🥙',
  pie: '🥧',
  dessert: '🍰',
  ice: '🍦',
  chocolate: '🍫',
  wine: '🍷',
  beer: '🍺',
  soup: '🍲',
  beverage: '🥤',
  bill: '🧾',
  menu: '📋',
  recipe: '📖',
  ingredient: '🥕',
  taste: '👅',
  cook: '👨‍🍳',
  waiter: '🧑‍🍳',
  airplane: '✈️',
  airport: '🛫',
  train: '🚆',
  bus: '🚌',
  car: '🚗',
  taxi: '🚕',
  port: '⚓',
  harbor: '⚓',
  ship: '🚢',
  hotel: '🏨',
  room: '🛏️',
  passport: '🛂',
  ticket: '🎫',
  map: '🗺️',
  street: '🛣️',
  square: '🏛️',
  beach: '🏖️',
  sea: '🌊',
  mountain: '⛰️',
  island: '🏝️',
  luggage: '🧳',
  suitcase: '🧳',
  station: '🚉',
  trip: '🧳',
  left: '⬅️',
  right: '➡️',
  straight: '⬆️',
  reservation: '📅',
  driver: '🚗',
  guide: '🧭',
  landmark: '🗺️',
  tourist: '📸',
  departure: '🛫',
  arrival: '🛬',
  sidewalk: '🚶',
  bridge: '🌉',
  cruise: '🚢',
  international: '🌍',
  borders: '🛂',
  country: '🌍',
  school: '🏫',
  student: '🎓',
  teacher: '👩‍🏫',
  book: '📖',
  notebook: '📓',
  pencil: '✏️',
  pen: '🖊️',
  lesson: '📖',
  exam: '📝',
  university: '🎓',
  classroom: '🏫',
  desk: '🪑',
  board: '📋',
  mathematics: '➗',
  history: '📜',
  language: '🗣️',
  science: '🔬',
  art: '🎨',
  music: '🎵',
  library: '📚',
  homework: '📝',
  paper: '📄',
  backpack: '🎒',
  teaching: '👩‍🏫',
  learning: '📚',
  notes: '📝',
  grade: '📊',
  lab: '🧪',
  lecture: '🎓',
  educator: '👩‍🏫',
  knowledge: '💡',
  idea: '💡',
  question: '❓',
  family: '👨‍👩‍👧',
  mother: '👩',
  father: '👨',
  son: '👦',
  daughter: '👧',
  brother: '👦',
  sister: '👧',
  grandfather: '👴',
  grandmother: '👵',
  spouse: '💍',
  child: '🧒',
  baby: '👶',
  uncle: '👨',
  aunt: '👩',
  cousin: '🧑',
  parents: '👨‍👩‍👧',
  relative: '👪',
  friend: '🤝',
  neighbor: '🏘️',
  relationship: '💑',
  wedding: '💒',
  couple: '💑',
  house: '🏠',
  apartment: '🏢',
  kitchen: '🍳',
  bathroom: '🚿',
  bedroom: '🛏️',
  door: '🚪',
  window: '🪟',
  bed: '🛏️',
  chair: '🪑',
  table: '🪑',
  lamp: '💡',
  refrigerator: '🧊',
  oven: '🔥',
  key: '🔑',
  garden: '🌻',
  corner: '📐',
  floor: '🪵',
  wall: '🧱',
  balcony: '🏠',
  broom: '🧹',
  soap: '🧼',
  towel: '🛁',
  head: '🗣️',
  eye: '👁️',
  ear: '👂',
  nose: '👃',
  mouth: '👄',
  tooth: '🦷',
  hand: '✋',
  foot: '🦶',
  heart: '❤️',
  hair: '💇',
  face: '🙂',
  neck: '🧍',
  back: '🔙',
  stomach: '🫃',
  finger: '☝️',
  knee: '🦵',
  shoulder: '💪',
  health: '💚',
  pain: '😣',
  illness: '🤒',
  doctor: '👨‍⚕️',
  hospital: '🏥',
  medicine: '💊',
  blood: '🩸',
  nurse: '👩‍⚕️',
  dentist: '🦷',
  smell: '👃',
  voice: '🗣️',
  one: '1️⃣',
  two: '2️⃣',
  three: '3️⃣',
  four: '4️⃣',
  five: '5️⃣',
  six: '6️⃣',
  seven: '7️⃣',
  eight: '8️⃣',
  nine: '9️⃣',
  ten: '🔟',
  twenty: '2️⃣',
  thirty: '3️⃣',
  hundred: '💯',
  thousand: '🔢',
  first: '🥇',
  second: '🥈',
  third: '🥉',
  half: '½',
  many: '📚',
  little: '🤏',
  red: '🔴',
  blue: '🔵',
  green: '🟢',
  yellow: '🟡',
  black: '⚫',
  white: '⚪',
  purple: '🟣',
  pink: '🩷',
  brown: '🟤',
  gray: '⚪',
  gold: '🥇',
  silver: '🥈',
  color: '🎨',
  dark: '🌑',
  light: '💡',
  hour: '⏰',
  minute: '⏱️',
  day: '📅',
  today: '📅',
  tomorrow: '➡️',
  yesterday: '⬅️',
  week: '📆',
  month: '📆',
  year: '📆',
  now: '⏰',
  early: '🌅',
  late: '🌙',
  time: '⏰',
  clock: '🕐',
  watch: '⌚',
  calendar: '📅',
  winter: '❄️',
  spring: '🌸',
  summer: '☀️',
  autumn: '🍂',
  monday: '📅',
  sunday: '📅',
  weather: '🌤️',
  sun: '☀️',
  rain: '🌧️',
  snow: '❄️',
  cloud: '☁️',
  wind: '💨',
  heat: '🥵',
  cold: '🥶',
  storm: '⛈️',
  sky: '🌤️',
  temperature: '🌡️',
  humidity: '💧',
  fog: '🌫️',
  thunderstorm: '⛈️',
  fire: '🔥',
  market: '🏪',
  shop: '🏪',
  price: '🏷️',
  money: '💶',
  euro: '💶',
  change: '🪙',
  discount: '🏷️',
  sale: '🛍️',
  bag: '👜',
  clothes: '👕',
  shoe: '👟',
  size: '📏',
  quality: '⭐',
  customer: '🧑',
  receipt: '🧾',
  groceries: '🛒',
  joy: '😊',
  sadness: '😢',
  fear: '😨',
  anger: '😠',
  happiness: '😊',
  worry: '😟',
  surprise: '😲',
  love: '❤️',
  hope: '🌟',
  shame: '😳',
  pride: '🦁',
  calm: '😌',
  nervous: '😰',
  happy: '😊',
  sad: '😢',
  tired: '😴',
  excited: '🤩',
  anxious: '😰',
  dog: '🐕',
  cat: '🐈',
  bird: '🐦',
  horse: '🐴',
  cow: '🐄',
  sheep: '🐑',
  goat: '🐐',
  rabbit: '🐇',
  mouse: '🐭',
  lion: '🦁',
  elephant: '🐘',
  dolphin: '🐬',
  turtle: '🐢',
  bee: '🐝',
  insect: '🐛',
  animal: '🐾',
  donkey: '🫏',
  work: '💼',
  job: '💼',
  office: '🏢',
  company: '🏢',
  salary: '💰',
  colleague: '👥',
  boss: '👔',
  interview: '🎤',
  contract: '📄',
  deadline: '⏰',
  planning: '📋',
  meeting: '👥',
  email: '📧',
  telephone: '☎️',
  computer: '💻',
  director: '👔',
  employee: '🧑‍💼',
  profession: '💼',
  career: '📈',
  schedule: '📅',
  nature: '🌿',
  tree: '🌳',
  flower: '🌸',
  grass: '🌱',
  forest: '🌲',
  river: '🏞️',
  lake: '🏞️',
  moon: '🌙',
  star: '⭐',
  stone: '🪨',
  sand: '🏖️',
  earth: '🌍',
  plant: '🌱',
  environment: '🌍',
  city: '🏙️',
  village: '🏘️',
  center: '🏙️',
  downtown: '🏙️',
  park: '🌳',
  museum: '🏛️',
  church: '⛪',
  police: '👮',
  firefighter: '🚒',
  bank: '🏦',
  pharmacy: '💊',
  stop: '🚏',
  café: '☕',
  restaurant: '🍽️',
  building: '🏢',
  neighborhood: '🏘️',
  pedestrian: '🚶',
  good: '👍',
  bad: '👎',
  big: '📏',
  small: '🤏',
  new: '✨',
  old: '📜',
  beautiful: '✨',
  ugly: '😕',
  fast: '⚡',
  slow: '🐢',
  easy: '✅',
  difficult: '🧩',
  correct: '✅',
  wrong: '❌',
  expensive: '💸',
  cheap: '💰',
  full: '📦',
  empty: '📭',
  warm: '🌡️',
  hot: '🔥',
  clean: '✨',
  dirty: '🧹',
  quiet: '🤫',
  noisy: '🔊',
  important: '❗',
  phone: '📱',
  mobile: '📱',
  internet: '🌐',
  website: '🌐',
  password: '🔐',
  screen: '🖥️',
  keyboard: '⌨️',
  camera: '📷',
  photo: '📷',
  video: '🎬',
  app: '📱',
  message: '💬',
  sports: '⚽',
  football: '⚽',
  soccer: '⚽',
  ball: '⚽',
  team: '👥',
  match: '🏆',
  game: '🎮',
  victory: '🏆',
  defeat: '😞',
  player: '🏃',
  coach: '📣',
  gym: '🏋️',
  swimming: '🏊',
  running: '🏃',
  walking: '🚶',
  exercise: '🏃',
  greece: '🇬🇷',
  greek: '🇬🇷',
  tradition: '🏛️',
  theater: '🎭',
  cinema: '🎬',
  dance: '💃',
  celebration: '🎉',
  culture: '🏛️',
  myth: '🏛️',
  temple: '🛕',
  ancient: '🏛️',
  modern: '🏙️',
  global: '🌍',
  local: '📍',
  emergency: '🚨',
  help: '🆘',
  pharmacist: '💊',
  silence: '🤫',
  noise: '🔊',
  letter: '✉️',
  mail: '✉️',
  number: '🔢',
  total: '🔢',
  average: '📊',
  percentage: '％',
  rule: '📏',
  law: '⚖️',
  justice: '⚖️',
  freedom: '🕊️',
  peace: '☮️',
  war: '⚔️',
  athens: '🏛️',
  thessaloniki: '🏛️',
  crete: '🏝️',
  santorini: '🏝️',
  mykonos: '🏝️',
  parthenon: '🏛️',
  acropolis: '🏛️',
  umbrella: '☂️',
  hat: '👒',
  coat: '🧥',
  dress: '👗',
  pants: '👖',
  trousers: '👖',
  shirt: '👕',
  wallet: '👛',
  gasoline: '⛽',
  electricity: '⚡',
  birthday: '🎂',
  cake: '🎂',
  candle: '🕯️',
  gift: '🎁',
  christmas: '🎄',
  easter: '🐣',
  pizza: '🍕',
  pasta: '🍝',
  yogurt: '🥛',
  butter: '🧈',
  lemon: '🍋',
  strawberry: '🍓',
  watermelon: '🍉',
  grape: '🍇',
  cherry: '🍒',
  peach: '🍑',
  pork: '🥓',
  beef: '🥩',
  lamb: '🍖',
  shrimp: '🦐',
  octopus: '🐙',
  squid: '🦑',
  traffic: '🚦',
  rent: '🏠',
  heating: '🔥',
  blanket: '🛏️',
  pillow: '🛏️',
  mirror: '🪞',
  closet: '👔',
  wardrobe: '👔',
  trash: '🗑️',
  recycling: '♻️',
  pollution: '🏭',
  thunder: '⛈️',
  lightning: '⚡',
  party: '🎉',
  password: '🔐',
  player: '🏃',
  coach: '📣',
  word: '📖',
}

const STOP_WORDS = new Set([
  'i',
  'a',
  'an',
  'the',
  'am',
  'is',
  'are',
  'my',
  'your',
  'how',
  'you',
  'it',
  'to',
  'in',
  'on',
  'at',
  'be',
  'do',
  'me',
  'we',
  'he',
  'she',
  'this',
  'that',
  'very',
  'much',
  'does',
  'have',
  'nice',
  'meet',
  'doing',
  'well',
  'polite',
  'formal',
  'colloquial',
  'male',
  'female',
  'device',
  'use',
  'avoided',
  'with',
  'for',
  'and',
  'or',
  'not',
])

const SINGLE_WORD_EMOJI = {
  no: '❌',
  yes: '✅',
}

function keywordsFromEnglish(english) {
  const cleaned = english
    .toLowerCase()
    .replace(/\([^)]*\)/g, '')
    .replace(/[^a-z0-9\s]/g, ' ')

  const words = cleaned.split(/\s+/).filter((w) => w.length > 1 && !STOP_WORDS.has(w))
  return [...new Set(words)].sort((a, b) => b.length - a.length)
}

function keywordFromEnglish(english) {
  const words = keywordsFromEnglish(english)
  return words[0] || 'word'
}

function emojiFromPhrases(englishLower) {
  for (const [phrase, emoji] of Object.entries(PHRASE_EMOJI)) {
    if (englishLower.includes(phrase)) return emoji
  }
  return null
}

function emojiFromKeywords(english) {
  const lower = english.toLowerCase().trim()
  if (SINGLE_WORD_EMOJI[lower]) return SINGLE_WORD_EMOJI[lower]

  const fromPhrase = emojiFromPhrases(lower)
  if (fromPhrase) return fromPhrase

  for (const word of keywordsFromEnglish(english)) {
    if (KEYWORD_EMOJI[word]) return KEYWORD_EMOJI[word]
  }
  return null
}

/**
 * Primary visual for a vocabulary card (emoji illustration, no network).
 * @param {{ english: string, category: string }} card
 */
export function getVisualForCard(card) {
  const emoji =
    emojiFromKeywords(card.english) ??
    CATEGORY_EMOJI[card.category] ??
    '📖'

  return {
    emoji,
    keyword: keywordFromEnglish(card.english),
  }
}

export function getEmojiForCard(card) {
  return getVisualForCard(card).emoji
}

export { keywordFromEnglish, keywordsFromEnglish }
